import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Allerta_Stencil } from "next/font/google";
import "./globals.css";
import AppContainer from "@/components/AppContainer";

const allertaStencil = Allerta_Stencil({
  variable: "--font-allerta-stencil",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${allertaStencil.variable} min-h-screen`}
      >
        <AppContainer>{children}</AppContainer>
      </body>
    </html>
  );
}
