import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./particles.css";
import AppContainer from "@/components/AppContainer";

const allertaStencil = localFont({
  src: "./fonts/allerta-stencil-latin.woff2",
  variable: "--font-allerta-stencil",
  weight: "400",
  style: "normal",
});

const geistSans = localFont({
  src: "./fonts/geist-sans-latin.woff2",
  variable: "--font-geist-sans",
  style: "normal",
});

const geistMono = localFont({
  src: "./fonts/geist-mono-latin.woff2",
  variable: "--font-geist-mono",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${allertaStencil.variable} min-h-screen`}
      >
        <AppContainer>{children}</AppContainer>
      </body>
    </html>
  );
}
