import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./particles.css";
import "./deep-trauma-gradient.css";
import AppContainer from "@/components/layout/AppContainer";
import PhoneStatusBar from "@/components/layout/PhoneStatusBar";

const allertaStencil = localFont({
  src: "./fonts/allerta-stencil-latin.woff2",
  variable: "--font-allerta-stencil",
  weight: "400",
  style: "normal",
});

const geistSans = localFont({
  src: "./fonts/geist-sans-latin.woff2",
  variable: "--font-geist-sans",
  style: "normal",
});

const geistMono = localFont({
  src: "./fonts/geist-mono-latin.woff2",
  variable: "--font-geist-mono",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${allertaStencil.variable} min-h-screen`}
      >
        <div className="mx-auto w-full sm:w-[min(430px,52vh)] sm:rounded-[2rem] sm:bg-slate-950 sm:p-[10px] sm:shadow-2xl">
          <PhoneStatusBar />

          <div className="phone-screen sm:h-[calc(100vh-20.25rem)] sm:overflow-y-auto sm:rounded-b-[1.35rem]">
            <AppContainer>{children}</AppContainer>
          </div>
        </div>
      </body>
    </html>
  );
}
